title: Thibault Simon
email: thibault.simon@orange.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a PhD candidate working on software environmental footprint in the Spirals team at Inria Lille and Orange Innovation in Rennes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thibaultsimon.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tibo_smn
github_username: tibosmn

favicon: "assets/favicon.png"
# Build settings
remote_theme: riggraz/no-style-please
plugins:
  # - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
